org.gradle.jvmargs=-Xmx4G -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant
android.useAndroidX=true
android.enableJetifier=true
android.enableR8.fullMode=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
kotlin.incremental=false
kotlin.caching.enabled=false
android.enableBuildCache=true