// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFynOb7cl555DkSCO0I4C51nEFGAEqpgc',
    appId: '1:1065762459264:web:3cb60f2efd86c03733e065',
    messagingSenderId: '1065762459264',
    projectId: 'dt-live-web',
    authDomain: 'dt-live-web.firebaseapp.com',
    storageBucket: 'dt-live-web.firebasestorage.app',
    measurementId: 'G-BR9BQYS8H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNWWf7Pl72z_RgaaKBegVRD5_gLKC8I-w',
    appId: '1:1065762459264:android:142247becdda683833e065',
    messagingSenderId: '1065762459264',
    projectId: 'dt-live-web',
    storageBucket: 'dt-live-web.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8jn4UqFpX2aIgRCFRwZx-qdpH4jJi8k',
    appId: '1:1065762459264:ios:dbd68cc36de4802333e065',
    messagingSenderId: '1065762459264',
    projectId: 'dt-live-web',
    storageBucket: 'dt-live-web.firebasestorage.app',
    iosClientId: '1065762459264-7u17lfrtni8rim4bkdr1dliiqk6pm524.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourappname',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl8jn4UqFpX2aIgRCFRwZx-qdpH4jJi8k',
    appId: '1:1065762459264:ios:dbd68cc36de4802333e065',
    messagingSenderId: '1065762459264',
    projectId: 'dt-live-web',
    storageBucket: 'dt-live-web.firebasestorage.app',
    iosClientId: '1065762459264-7u17lfrtni8rim4bkdr1dliiqk6pm524.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourappname',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFynOb7cl555DkSCO0I4C51nEFGAEqpgc',
    appId: '1:1065762459264:web:ffc27251244d8a6f33e065',
    messagingSenderId: '1065762459264',
    projectId: 'dt-live-web',
    authDomain: 'dt-live-web.firebaseapp.com',
    storageBucket: 'dt-live-web.firebasestorage.app',
    measurementId: 'G-PVZ24TR7FH',
  );

}